<?php declare(strict_types=1);

/*
 * This file is part of Biurad opensource projects.
 *
 * @copyright 2022 Biurad Group (https://biurad.com/)
 * @license   https://opensource.org/licenses/BSD-3-Clause License
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Biurad\Loader\Files\Adapters;

use Nette\Neon;

/**
 * Reading and generating NEON files.
 *
 * @author Divine Niiquaye Ibok <divineibok@gmail.com>
 */
final class NeonFileAdapter extends AbstractAdapter
{
    public function supports(string $file): bool
    {
        return 'neon' === \strtolower(\pathinfo($file, \PATHINFO_EXTENSION));
    }

    /**
     * Reads configuration from NEON data.
     */
    protected function processFrom(string $string): array
    {
        return Neon\Neon::decode($string);
    }

    /**
     * Generates configuration in NEON format.
     */
    protected function processDump(array $data): string
    {
        $class = __CLASS__;

        return "# generated by $class\n\n".Neon\Neon::encode(
            $data,
            Neon\Neon::BLOCK,
            "  "
        );
    }
}
